name: GitHub Actions Demo
on: [push]
jobs:
  To-Ankiaddon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: >
          zip -r MDKaTeX.zip MDKaTeX
          mv MDKaTeX.zip MDKaTeX.ankiaddon