name: GitHub Actions Demo
on: [push]
jobs:
  To-Ankiaddon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create ankiaddon
        run: |
          ls
          zip -r -q MDKaTeX.zip MDKaTeX
          mv MDKaTeX.zip MDKaTeX.ankiaddon
          ls
      
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MDKaTeX.ankiaddon
          asset_name: MDKaTeX.ankiaddon
          asset_content_type: application/gzip
