name: GitHub Actions Demo
on: [push]
jobs:
  To-Ankiaddon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - run: zip -r -q MDKaTeX.zip MDKaTeX
      - run: mv MDKaTeX.zip MDKaTeX.ankiaddon
      - run: ls